import Head from "next/head";
import { Home } from "../components/Home/Home";

export default function Index() {
  return (
    <>
      <Head>
        <title>Start with us books.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />
    </>
  );
}

//https://dribbble.com/shots/18052378-Book-Collection-Header-Page-UI
// https://dribbble.com/shots/16139970-Piqoboo-Book-Landing-Page
//https://dribbble.com/shots/19582832-Library-Management-Dashboard

//login , local library relink to local libraries map
