import Head from "next/head";
import { PrivateRoute } from "../../routes/PrivateRoute";

export default function Index() {
  return (
    <>
      <Head>
        <title>Books manager.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PrivateRoute is={true}>
        <h1>Manager access</h1>
      </PrivateRoute>
    </>
  );
}
