import Head from "next/head";
import { SignLibrary } from "../../components/Sign/SignLibrary";

export default function Index() {
  return (
    <>
      <Head>
        <title>Sign a library.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SignLibrary />
    </>
  );
}
